# Generated by Django 5.0.1 on 2024-11-27 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_member_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_Number', models.CharField(blank=True, max_length=30, null=True)),
                ('img_main', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(blank=True, max_length=30, null=True)),
                ('Last_Name', models.CharField(blank=True, max_length=30, null=True)),
                ('Card_Number', models.IntegerField(blank=True, null=True)),
                ('Security_Code', models.IntegerField(blank=True, null=True)),
                ('Billing_Street', models.CharField(blank=True, max_length=100, null=True)),
                ('Member', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='product',
        ),
    ]
