# Generated by Django 5.0.1 on 2024-11-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_item_action_item_barrel_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Sale_Ends',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
