# Generated by Django 5.0.1 on 2024-12-31 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_confirmed_potential_delete_item_delete_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='potential',
            old_name='Name',
            new_name='Company',
        ),
    ]
