# Generated by Django 5.0.1 on 2024-10-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_main', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
