# Generated by Django 5.0.1 on 2024-11-11 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_club_member_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='Email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
