# Generated by Django 5.0.1 on 2024-11-27 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_item_payment_method_delete_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment_Method',
        ),
    ]
