# Generated by Django 5.0.1 on 2024-11-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_item_caliber_item_capacity_item_dealer_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Action',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='Barrel_length',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
